[manager]
ratio         = [ 1, 3, 4 ]
sort_by        = "alphabetical"
sort_sensitive = true
sort_reverse   = false
sort_dir_first = true
show_hidden    = true
show_symlink   = true
linemode       = "size"

[preview]
tab_size        = 2
max_width       = 600
max_height      = 900
image_quality   = 75
sixel_fraction  = 15
ueberzug_scale  = 1
ueberzug_offset = [ 0, 0, 0, 0 ]
cache_dir = "/home/dk/.cache/yazi"

[opener]
folder = [
  { exec = '$EDITOR "$@"', block = true },
]

unzip = [
  { exec = 'mcomix "$@"' },
  { exec = 'unzip -d "${file%.*}" "$file"', desc = "Extract here" },
  { exec = 'unzip -O sjis -d "${file%.*}" "$file"', desc = "Extract here (SJIS)" },
]
unrar = [
  { exec = 'mcomix "$@"' },
  { exec = 'unrar x "$1" "${1%.*}/', desc = "Extract here" },
]
text = [
  { exec = '$EDITOR "$@"', block = true },
]
image = [
  { exec = 'feh "$@"', desc = "feh to read images" },
]
media = [
  { exec = 'mpv "$@"', desc = "mpv" },
  { exec = 'mpv -v "$@"', desc = "mpv (verbose)", block = true },
  { exec = 'mpv --profile=headphone "$@"', desc = "mpv (headphone)" },
  { exec = 'mpv --profile=surround-hdmi "$@"', desc = "mpv (hdmi)" },
  { exec = 'mpv --profile=bt "$@"', desc = "mpv (bt)" },
  { exec = 'mpv --profile=jack "$@"', desc = "mpv (jack)" },
]

pdf = [
  { exec = 'zathura "$@"', desc = "read pdf file" },
]

fallback = [
  { exec = 'open "$@"', desc = "Open" },
  { exec = 'open -R "$@"', desc = "Reveal in Finder" },
]

[open]
rules = [
  { name = "*/", use = "folder" },
  { mime = "text/*", use = "text" },
  { mime = "image/*", use = "image" },
  { mime = "video/*", use = "media" },
  { mime = "audio/*", use = "media" },
  { mime = "inode/x-empty", use = "text" },

  { mime = "application/json", use = "text" },
  { mime = "application/pdf", use = "pdf" },
  { mime = "*/javascript", use = "text" },

  { mime = "application/zip", use = "unzip" },
  { mime = "application/x-rar", use = "unrar" },
  { mime = "*", use = "fallback" },
]

# [tasks]
# micro_workers    = 20
# macro_workers    = 25
# bizarre_retry    = 5
# image_alloc      = 536870912  # 512MB
# image_bound      = [ 2048, 2048 ]
# suppress_preload = false
