# encoding: utf-8
# -*- mode: ruby -*-
# vi: set ft=ruby :
# Box / OS
VAGRANT_BOX = 'ubuntu/trusty64'
# Memorable name for your
VM_NAME = 'ubu'
# VM User — 'vagrant' by default
VM_USER = 'ubu-dk'
# Username on your Mac
_USER = 'dk'
# Host folder to sync
HOST_PATH = '~/vagrant/shared/' + _USER + '/' + VM_NAME
# Where to sync to on Guest — 'vagrant' is the default user name
GUEST_PATH = '/home/' + VM_USER + '/' + VM_NAME
# # VM Port — uncomment this to use NAT instead of DHCP
# VM_PORT = 8080
Vagrant.configure(2) do |config|
  # Vagrant box from Hashicorp
  config.vm.box = VAGRANT_BOX
  
  # Actual machine name
  config.vm.hostname = VM_NAME
  # Set VM name in Virtualbox
  config.vm.provider "virtualbox" do |v|
    v.name = VM_NAME
    v.memory = 2048
  end
  #DHCP — comment this out if planning on using NAT instead
  config.vm.network "private_network", type: "dhcp"
  # # Port forwarding — uncomment this to use NAT instead of DHCP
  # config.vm.network "forwarded_port", guest: 80, host: VM_PORT
  # Sync folder
  config.vm.synced_folder HOST_PATH, GUEST_PATH
  # Disable default Vagrant folder, use a unique path per project
  config.vm.synced_folder '.', '/home/' + VM_USER + '', disabled: true

  # https://www.vagrantup.com/docs/provisioning/docker
  # # require plugin https://github.com/leighmcculloch/vagrant-docker-compose
  # config.vagrant.plugins = "vagrant-docker-compose"

  # # install docker and docker-compose
  # config.vm.provision :docker
  # config.vm.provision :docker_compose

  # Install Essential devs/bins stufs,
  config.vm.provision "shell", inline: <<-SHELL
    # Casual apt update/installations
    apt-get update -y
    apt-get install -y --force-yes \
      git vim curl \
      lsb-release \
      ca-certificates \
      build-essential \
      apt-transport-https \
      software-properties-common
    apt-get autoremove -y
  SHELL
end
